In [64]:
%reset -f
import numpy as np

In [65]:
def find_smallest_repeat(arr):
    n = len(arr)
    # 1. Find all divisors of the length (15 -> 1, 3, 5, 15)
    for d in range(1, n + 1):
        if n % d == 0:
            # 2. Extract the potential base pattern
            base = arr[:d]
            # 3. Tile it to the original length and compare
            if np.array_equal(np.tile(base, n // d), arr):
                return d
    return n

In [66]:
def get_canonical_root(items):
    """
    Finds the lexicographically smallest cyclic shift of a sequence.
    Works for strings, numbers, or bits.
    """
    if not items:
        return items
    
    n = len(items)
    # Generate all cyclic rotations of the sequence
    rotations = [items[i:] + items[:i] for i in range(n)]
    
    # Return the "smallest" rotation as a tuple (so it can be put in a set)
    return min(rotations)

def count_root_codewords_from_grid(file_path):
    unique_roots = set()
    
    try:
        with open(file_path, 'r') as file:
            for line in file:
                # 1. Split line by commas to get individual bits
                # 2. Strip whitespace from each bit
                bits = [bit.strip() for bit in line.split(',') if bit.strip()]
                
                # If the line wasn't empty
                if bits:
                    # 3. Convert bits to a tuple (a 'fixed' list)
                    codeword = tuple(bits)
                    
                    # 4. Find the 'root' and add to our unique collection
                    root = get_canonical_root(codeword)
                    unique_roots.add(root)
                    
        return len(unique_roots), unique_roots

    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
        return 0

# --- Example Usage ---
# If codewords.txt contains:
# 0, 1, 1
# 1, 1, 0
# 1, 0, 1
# 0, 0, 1
# result will be 2 (Roots: (0, 0, 1) and (0, 1, 1))



In [79]:
filename = '../output/K15N30/message_14.txt'
count, unique_roots = count_root_codewords_from_grid(filename)
print(f"Number of root messages: {count}")
for r in unique_roots:
  s = " ".join(r)
  root = np.array([int(x) for x in s.split()])
  period = find_smallest_repeat(root)

  print(root, ", period: ", period)

Number of root messages: 42
[0 0 0 1 0 0 1 0 1 1 0 1 0 0 1] , period:  15
[0 0 1 1 0 1 0 1 1 0 0 1 1 1 1] , period:  15
[0 0 0 0 1 1 0 0 0 1 0 1 1 1 1] , period:  15
[0 0 0 0 0 1 0 1 0 1 1 0 1 0 1] , period:  15
[0 0 0 0 0 1 0 0 0 0 0 1 1 1 1] , period:  15
[0 0 0 1 1 1 1 0 0 1 0 0 1 0 1] , period:  15
[0 0 0 0 0 0 1 0 1 1 0 1 0 1 1] , period:  15
[0 0 0 0 0 1 0 1 1 0 0 1 0 0 1] , period:  15
[0 0 0 0 0 0 1 0 1 0 1 0 1 0 1] , period:  15
[0 0 1 0 0 1 1 0 1 1 1 1 1 1 1] , period:  15
[0 0 0 1 1 0 0 1 0 1 1 1 0 0 1] , period:  15
[0 0 0 0 1 0 0 1 0 0 0 0 1 0 1] , period:  15
[0 0 1 0 1 1 1 1 0 1 0 0 1 1 1] , period:  15
[0 0 0 0 0 0 0 0 1 0 1 1 1 0 1] , period:  15
[0 1 0 1 1 0 1 1 1 1 1 1 0 1 1] , period:  15
[0 0 0 1 0 0 1 0 1 0 1 0 1 1 1] , period:  15
[0 0 1 0 1 0 1 1 0 1 1 0 1 1 1] , period:  15
[0 0 0 0 1 1 1 1 0 1 0 0 0 1 1] , period:  15
[0 0 0 0 1 0 0 1 1 1 1 1 0 0 1] , period:  15
[0 0 0 1 1 1 0 1 0 1 0 1 0 0 1] , period:  15
[0 0 0 0 1 1 0 1 0 0 1 0 1 0 1] , period:  15
[0 0 0

In [4]:
lyndon_message = '../output/K15N30/tbcc_coset_leaders.txt'
count_lyndon, unique_roots_lyndon = count_root_codewords_from_grid(lyndon_message)
print(f"Number of root codewords: {count_lyndon}")

Number of root codewords: 3


In [12]:
lyndon_message = '../output/K15N30/lyndon_message_cwd_10.txt'
count_lyndon, unique_roots_lyndon = count_root_codewords_from_grid(lyndon_message)
print(f"Number of root codewords: {count_lyndon}")

Number of root codewords: 21


In [54]:
c_hat_modulated = np.array([-1,1,-1,-1,1,-1,-1,1,-1,-1,-1,-1,-1,-1,1,1,1,-1,-1,-1,1,-1,1,1,-1,1,1,-1,1,-1])
c_hat = (1-c_hat_modulated) // 2

c_modulated_ED_corrected_cwd = np.array([-1,-1,1,-1,-1,-1,1,1,-1,-1,-1,1,1,1,1,-1,-1,1,-1,1,-1,1,1,1,1,-1,-1,-1,1,-1], dtype=np.int32)
c_ED_corrected_cwd = (1-c_modulated_ED_corrected_cwd) // 2
check = np.array([1,1,0,1,1,1,0,0,1,1,1,0,0,0,0,1,1,0,1,0,1,0,0,0,0,1,1,1,0,1])
print(np.all(np.equal(check, c_ED_corrected_cwd)))

target = np.bitwise_xor(c_hat, c_ED_corrected_cwd)
print(target)

True
[0 1 1 0 1 0 1 0 0 0 0 1 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 0 0 0]


In [55]:
gabriel_neighbors = []
for dist in [8,10,12,14,16]:
  filename = "../output/K15N30/codeword_{}.txt".format(dist)
  with open(filename, 'r') as file:
    for line in file:
        # 1. Split line by commas to get individual bits
        # 2. Strip whitespace from each bit
        bits = [bit.strip() for bit in line.split(',') if bit.strip()]
        s = " ".join(bits)
        cwd = [int(x) for x in s.split()]
        gabriel_neighbors.append(np.array(cwd))
    
display(gabriel_neighbors[0])
a = np.array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1])

index = None
for i, x in enumerate(gabriel_neighbors):
    if np.array_equal(target, x):
        index = i
        break

exists = index is not None
print("index: ", index)
print(exists)

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1])

index:  None
False


In [14]:
temp = []
with open("../output/K15N30/coset_leaders.txt", 'r') as file:
  for line in file:
      # 1. Split line by commas to get individual bits
      # 2. Strip whitespace from each bit
      bits = [bit.strip() for bit in line.split(',') if bit.strip()]
      s = " ".join(bits)
      cwd = [int(x) for x in s.split()]
      temp.append(cwd)

coset_leaders = (1-np.array(temp))/2
print(coset_leaders)
np.savetxt("../output/K15N30/coset_leaders_cwds.txt", coset_leaders, fmt="%d", delimiter=" ")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 1.]]


In [53]:
a = np.array([-1,1,-1,-1,1,-1,-1,1,-1,-1,-1,-1,-1,-1,1,1,1,-1,-1,-1,1,-1,1,1,-1,1,1,-1,1,-1])
r = np.array([-3.27,-0.41,-1.37,-2.27,0.95,-2.79,-0.21,1.80,-3.14,-2.45,-2.28,-0.00,0.63,1.34,1.31,-0.36,2.43,0.19,-0.90,-0.09,0.81,-0.83,0.92,0.40,-1.48,-2.76,1.93,-3.05,2.30,-0.57])

bch = np.array([1,1,-1,-1])
print(np.sum(a*r))


31.86


In [60]:
import itertools 
print(np.array(list(itertools.product([0,1,2,3], repeat=4))))

[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 2]
 ...
 [3 3 3 1]
 [3 3 3 2]
 [3 3 3 3]]


In [62]:
N = 30
K = 11
# EsNo
esno_dB = np.arange(-5,2,0.1)
esno_linear = 10**(esno_dB/10)
# EbNo
ebno_linear = esno_linear * N / K
ebno_dB = 10 * np.log10(ebno_linear)
# Es/sigma^2
es_over_sigma_sqrd_linear = esno_linear * 2
es_over_sigma_sqrd_dB = 10*np.log10(es_over_sigma_sqrd_linear)
display(es_over_sigma_sqrd_dB)

array([-1.98970004, -1.88970004, -1.78970004, -1.68970004, -1.58970004,
       -1.48970004, -1.38970004, -1.28970004, -1.18970004, -1.08970004,
       -0.98970004, -0.88970004, -0.78970004, -0.68970004, -0.58970004,
       -0.48970004, -0.38970004, -0.28970004, -0.18970004, -0.08970004,
        0.01029996,  0.11029996,  0.21029996,  0.31029996,  0.41029996,
        0.51029996,  0.61029996,  0.71029996,  0.81029996,  0.91029996,
        1.01029996,  1.11029996,  1.21029996,  1.31029996,  1.41029996,
        1.51029996,  1.61029996,  1.71029996,  1.81029996,  1.91029996,
        2.01029996,  2.11029996,  2.21029996,  2.31029996,  2.41029996,
        2.51029996,  2.61029996,  2.71029996,  2.81029996,  2.91029996,
        3.01029996,  3.11029996,  3.21029996,  3.31029996,  3.41029996,
        3.51029996,  3.61029996,  3.71029996,  3.81029996,  3.91029996,
        4.01029996,  4.11029996,  4.21029996,  4.31029996,  4.41029996,
        4.51029996,  4.61029996,  4.71029996,  4.81029996,  4.91